## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [50]:
import numpy as np

#1.)
V1 = np.arange(5,11,1)
V2 = np.arange(15,21,1)
print (V1)
print (V2, '\n')
#2.) A.

M1 = np.zeros( (len(V1), len(V2)) ) #allocating array of zeros

for i in range(len(V1)):
  for j in range(len(V2)):
    M1 [i,j] = V1[i] * V2[j]
    
print (M1)
    
#B)
tr = 0

for i in range(len(V1)):
  for j in range(len(V2)):
    if i == j:
      tr = tr + M1[i,j]

      
print ('\n The "trace", tr(A) equals %d \n' %tr)



#The same operations using numpy operations:
#2A

M2 = np.outer(V1, V2)
print (M2)

#2B)
Trace = np.trace(M2)
print ('The "trace", tr(A) equals', Trace)

[ 5  6  7  8  9 10]
[15 16 17 18 19 20] 

[[ 75.  80.  85.  90.  95. 100.]
 [ 90.  96. 102. 108. 114. 120.]
 [105. 112. 119. 126. 133. 140.]
 [120. 128. 136. 144. 152. 160.]
 [135. 144. 153. 162. 171. 180.]
 [150. 160. 170. 180. 190. 200.]]

 The "trace", tr(A) equals 805 

[[ 75  80  85  90  95 100]
 [ 90  96 102 108 114 120]
 [105 112 119 126 133 140]
 [120 128 136 144 152 160]
 [135 144 153 162 171 180]
 [150 160 170 180 190 200]]
The "trace", tr(A) equals 805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [148]:
import random
#1

[m,n] = [4,3] 
mA = np.random.randint(0,101,(m,n)) #creates matrix with random numbers between 0 and 100
mB = np.random.randint(0,101,(n,m))

print (mA, '\n')
print (mB, '\n')
mC = np.zeros([m,m], dtype = 'int64') #Use [] or () in this case??


#A
for i in range (m):
    for j in range (m):        
        for k in range (n):
            mC[i,j] += mA[i,k] * mB[k,j]
print ('\n Multiplication of the two matrices by conventional for-loops gives this matrix:',mC)



#B

#mC = np.zeros([m,m], dtype = 'int32')


#for i in range(m)
#mC(i,j) = 
#c(i,j) = [for i in range(m)  ]

#for i in list:
 #   if conditional:
  #      expression
        
#[ expression for i in list if conditional ]

#C 
C = np.dot(mA,mB)
#print ('Numpy: \n', mC)

#2



[[ 8 96 67]
 [37 30 29]
 [32 30 40]
 [92 87 93]] 

[[ 6 49 70 78]
 [99 57 50 22]
 [27 81 38 77]] 


 Multiplication of the two matrices by conventional for-loops gives this matrix: [[11361 11291  7906  7895]
 [ 3975  5872  5192  5779]
 [ 4242  6518  5260  6236]
 [11676 17000 14324 16251]]


NameError: name 'A' is not defined